baseURL = "https://preeminent-alfajores-80fcb9.netlify.app"
title = "My personal place"
theme = "hugo-coder"
languagecode = "zh-cn"
defaultcontentlanguage = "zh-cn"

enableRobotsTXT = true
canonifyURLs = true

enableGitInfo = true
enableEmoji = true

paginate = 9999

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = false
pluralizelisttitles = false

FootnoteReturnLinkContents = "↑"

[markup.goldmark.renderer]
    unsafe= true

[outputs]
  page     = ["HTML", "AMP"]
  home     = ["HTML", "RSS"]
  section  = ["HTML"]
  taxonomyTerm = ["HTML"]
  taxonomy = ["HTML"]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[params]
author = ""
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "John Doe's personal website"
keywords = "blog,developer,personal"
info = ["终有一天", "你会跨过静谧无声的洗墨江", "离开群山环抱的旧桃源", "来到无边阴霾的夜空之下"]
avatarURL = "images/fawkes-mask.png"
dateFormat = "January 2, 2006"
since = 2022
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []


[languages]
    [languages.zh-cn]
        languagename = "Chinese"
        title = "专栏主人，半文盲"

        [languages.zh-cn.params]
        [languages.zh-cn.menu]
            [[languages.zh-cn.menu.main]]
                name = "关于"
                weight = 1
                url = "/about/"
            [[languages.zh-cn.menu.main]]
                name = "安卓"
                weight = 2
                url  = "/android/"
            [[languages.zh-cn.menu.main]]
                name = "工具"
                weight = 3
                url  = "/tools/"
            [[languages.zh-cn.menu.main]]
                name = "前端"
                weight = 4
                url  = "/web/"